baseURL = 'http://hugotestwebsiteportal.s3-website-us-east-1.amazonaws.com'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"
[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://hugotestwebsiteportal/?region=us-east-1" #your bucket here
